services:
  - type: web
    name: telegram-explain-bot
    env: python
    buildCommand: ""
    startCommand: "./start.sh"
    envVars:
      - key: TOKEN
        value: your_bot_token_here
      - key: API_KEY
        value: your_openrouter_api_key_here
